# PIM Settings Configuration
# This YAML file defines the Privileged Identity Management (PIM) settings used in the role assignment policies.

- id: default
  rules:
  - id: Expiration_Admin_Eligibility
    isExpirationRequired: false
  - id: Enablement_EndUser_Assignment
    enabledRules:
    - MultiFactorAuthentication
    - Justification

- id: default-approval
  rules:
  - id: Expiration_Admin_Eligibility
    isExpirationRequired: false
  - id: Enablement_EndUser_Assignment
    enabledRules:
    - MultiFactorAuthentication
    - Justification
  - id: Approval_EndUser_Assignment
    setting:
      isApprovalRequired: true
      isApprovalRequiredForExtension: false
      isRequestorJustificationRequired: true
      approvalMode: SingleStage
      approvalStages:
      - approvalStageTimeOutInDays: 1
        isApproverJustificationRequired: true
        escalationTimeInMinutes: 0
        isEscalationEnabled: false
        primaryApprovers:
        - id: <GUID of approval group 1>
          description: <Name of approval group 1>
          isBackup: false
          userType: Group
        - id: <GUID of approval group 2>
          description: <Name of approval group 2>
          isBackup: false
          userType: Group